packages:
  - "apps/*"
  - "packages/*"

catalog:
  "next": "^15"
  "react": "^19"
  "react-dom": "^19"
  "@types/node": "^22"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "tailwindcss": "^3"
  "postcss": "^8"
  "typescript": "^5"
